// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proxy/shield_proxy.proto

package yah_app_registry

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ShieldRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ShieldRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShieldRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ShieldRequestMultiError, or
// nil if none found.
func (m *ShieldRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ShieldRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Body

	// no validation rules for Queryparams

	if len(errors) > 0 {
		return ShieldRequestMultiError(errors)
	}

	return nil
}

// ShieldRequestMultiError is an error wrapping multiple validation errors
// returned by ShieldRequest.ValidateAll() if the designated constraints
// aren't met.
type ShieldRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShieldRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShieldRequestMultiError) AllErrors() []error { return m }

// ShieldRequestValidationError is the validation error returned by
// ShieldRequest.Validate if the designated constraints aren't met.
type ShieldRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShieldRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShieldRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShieldRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShieldRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShieldRequestValidationError) ErrorName() string { return "ShieldRequestValidationError" }

// Error satisfies the builtin error interface
func (e ShieldRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShieldRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShieldRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShieldRequestValidationError{}

// Validate checks the field values on ShieldReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ShieldReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShieldReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ShieldReplyMultiError, or
// nil if none found.
func (m *ShieldReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ShieldReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Err

	// no validation rules for Msg

	// no validation rules for Data

	// no validation rules for Status

	if len(errors) > 0 {
		return ShieldReplyMultiError(errors)
	}

	return nil
}

// ShieldReplyMultiError is an error wrapping multiple validation errors
// returned by ShieldReply.ValidateAll() if the designated constraints aren't met.
type ShieldReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShieldReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShieldReplyMultiError) AllErrors() []error { return m }

// ShieldReplyValidationError is the validation error returned by
// ShieldReply.Validate if the designated constraints aren't met.
type ShieldReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShieldReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShieldReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShieldReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShieldReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShieldReplyValidationError) ErrorName() string { return "ShieldReplyValidationError" }

// Error satisfies the builtin error interface
func (e ShieldReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShieldReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShieldReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShieldReplyValidationError{}
